Dynamic Programming Solution to 0-1 knapsack problem. 
<br />-Only one of each item, so no repetitive takes
<br />-Weights integers only<br /> 

Runtime = O(Wn) , where n is the number of items available to put in knapsack and W is weight limit.

In [6]:
import numpy as np
        
def knapsack(values = [20,5,10,40,15,25],
             weights = [1,2,3,8,7,4],
             W = 10):
    
    if len(values) != len(weights):
        print('values and weights arrays different lengths')
        exit()
    
    table = np.zeros((len(values)+1,W+1)) #Initialize table

    for i in range(1,table.shape[0]):
        for j in range(1,table.shape[1]):
            
            if weights[i-1] > j:
                table[i,j] = table[i-1,j]
            else:
                table[i,j] = max(table[i-1,j], table[i-1,j - weights[i-1]]+values[i-1])
                
    return table, table[table.shape[0]-1][table.shape[1]-1]



table,knapsack_value = knapsack()
print(table,'\n')
print('Max Knapsack Value =', knapsack_value)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
 [ 0. 20. 20. 25. 25. 25. 25. 25. 25. 25. 25.]
 [ 0. 20. 20. 25. 30. 30. 35. 35. 35. 35. 35.]
 [ 0. 20. 20. 25. 30. 30. 35. 35. 40. 60. 60.]
 [ 0. 20. 20. 25. 30. 30. 35. 35. 40. 60. 60.]
 [ 0. 20. 20. 25. 30. 45. 45. 50. 55. 60. 60.]] 

Max Knapsack Value = 60.0
