In [46]:
import numpy as np
        
    
def stable_matching(mens_pref, womens_pref):
    
    if np.count_nonzero(mens_pref==0) == 0 and np.count_nonzero(womens_pref==0) == 0: #force preferences to zero index if no zeros in either preference list
        mens_pref -= 1
        womens_pref -= 1
        print('Subtracting one from every entry in preference lists')
        print(mens_pref)
        print(womens_pref, '\n')
    
    free_men = np.arange(N)
    free_women = np.arange(N)
    ask_matrix = np.zeros((N,N)) #If ask_matrix[0,1] == 1, then man 0 has already proposed to woman 1
    S = np.zeros(N) #S[2]=3 -> woman 2 is married to man 3 
    
    while True:
        if (np.count_nonzero(ask_matrix) == N**2) or free_men.size == 0: break
    
        man = int(free_men[0])
        
        print(free_men.size)
        print('Processing free man', man)
        print('ask matrix:', ask_matrix)
        
        
        asked = np.where(ask_matrix[man]==1)
        if asked[0].size == 0:
            ask_index = -1
            print('first ask matrix entry')
        else:
            ask_index = asked[0][-1]
            
        if ask_index < N-1:
            for woman_index in range(ask_index+1, N): #moving in order of mans preference
                ask_matrix[man][woman_index] = 1
                woman = mens_pref[man][woman_index]
                if woman in free_women: #if woman is free she becomes engaged
                    S[woman] = man
                    free_men = np.delete(free_men, 0)
                    free_women = np.delete(free_women, np.where(free_women==woman)[0][0])
                    break
                else:
                    free_man_pref = (np.where(womens_pref[woman] == man))[0][0]
                    taken_man_pref = (np.where(womens_pref[woman] == S[woman]))[0][0]
                    if taken_man_pref < free_man_pref:
                        #Free man is less preferred than current husband
                        continue
                    else:
                        #Free man is more preferred than current husband
                        free_men = np.append(free_men, S[woman])
                        S[woman] = man
                        free_men = np.delete(free_men, 0)
                        break
    return(S)

N = 4
mens_pref = np.array([[2,4,1,3],  #Rows are each preference list
                      [3,1,4,2],
                      [2,3,1,4], 
                      [4,1,3,2]])
womens_pref = np.array([[2,1,4,3], #Rows are each preference list
                        [4,3,1,2], 
                        [1,4,3,2], 
                        [2,1,4,3]])

matching = stable_matching(mens_pref, womens_pref)
print(matching,'\n')

Subtracting one from every entry in preference lists
[[1 3 0 2]
 [2 0 3 1]
 [1 2 0 3]
 [3 0 2 1]]
[[1 0 3 2]
 [3 2 0 1]
 [0 3 2 1]
 [1 0 3 2]] 

4
Processing free man 0
ask matrix: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
first ask matrix entry
3
Processing free man 1
ask matrix: [[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
first ask matrix entry
2
Processing free man 2
ask matrix: [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
first ask matrix entry
2
Processing free man 3
ask matrix: [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
first ask matrix entry
1
Processing free man 0
ask matrix: [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
1
Processing free man 3
ask matrix: [[1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[3. 2. 1. 0.] 

