Dynamic Programming Solution to the length of the longest common subsequence problem. Subsequence defined as longest matching string that can be obtained from deleting chars from string 1, then deleting chars from string 2.

The longest common subsequence (LCS) problem is the problem of finding the longest subsequence that is present in given two sequences in the same order. i.e. find a longest sequence which can be obtained from the first original sequence by deleting some items, and from the second original sequence by deleting other items.

In [22]:
import numpy as np
        
def longest_common_subsequence(a = 'ABCBDAB', b = 'BDCABA'):
    table = np.zeros((len(a)+1,len(b)+1)) #Zero padded for initialization
    
    for i in range(1,table.shape[0]):
        for j in range(1,table.shape[1]):
            if b[j-1] == a[i-1]:
                table[i][j] = 1 + table[i-1][j-1]
            else:
                table[i][j] = max(table[i-1][j], table[i][j-1])
                
    return table, table[table.shape[0]-1][table.shape[1]-1]


table,lcs = longest_common_subsequence()
print(table,'\n')
print('Length of Longest Common Subsequence =', lcs)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 2. 2.]
 [0. 1. 1. 2. 2. 2. 2.]
 [0. 1. 1. 2. 2. 3. 3.]
 [0. 1. 2. 2. 2. 3. 3.]
 [0. 1. 2. 2. 3. 3. 4.]
 [0. 1. 2. 2. 3. 4. 4.]] 

Length of Longest Common Subsequence = 4.0
