Dynamic Programming Solution to the longest common subsequence problem. Subsequence defined as longest matching string that can be obtained from deleting chars from string 1, then deleting chars from string 2.

In [14]:
import numpy as np
        
def longest_common_subsequence(a = 'ABCBDAB', b = 'BDCABA'):
    table = np.zeros((len(a)+1,len(b)+1)) #Zero padded for initialization

    for i in range(1,table.shape[0]):
        for j in range(1,table.shape[1]):
            if b[j-1] == a[i-1]:
                table[i][j] = 1 + table[i-1][j-1]
            else:
                table[i][j] = max(table[i-1][j], table[i][j-1])
                
    return table, table[table.shape[0]-1][table.shape[1]-1]

%timeit table,lcs = longest_common_subsequence('ABXA', 'BDCABA')
print(table,'\n')
print('Length of Longest Common Subsequence =', lcs)

21.7 µs ± 156 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 2. 2.]
 [0. 1. 1. 1. 1. 2. 2.]
 [0. 1. 1. 1. 2. 2. 3.]] 

Length of Longest Common Subsequence = 3.0
