Dynamic Programming solution to obtain the levenshtein distance between two strings.

Runtime: O(mn) where m,n are the lengths of the input strings

In [9]:
import numpy as np
        
def levenshtein_distance(a = 'jab!', b = 'cab'):
    table = np.zeros((len(a)+1,len(b)+1)) #Initialize table
    for i in range(table.shape[0]):
        table[i,0] = i
    for j in range(table.shape[1]):
        table[0,j] = j

    for i in range(1,table.shape[0]):
        for j in range(1,table.shape[1]):
            cost = 1
            if a[i-1] == b[j-1] and (i-j==0): cost = 0
            
            table[i,j] = cost + min(table[i-1,j], table[i,j-1], table[i-1,j-1])
                
    return table, table[table.shape[0]-1][table.shape[1]-1]

table,lev_dist = levenshtein_distance()
print(table,'\n')
print('Levenshtein Distance =', lev_dist)

[[0. 1. 2. 3.]
 [1. 1. 2. 3.]
 [2. 2. 1. 2.]
 [3. 3. 2. 1.]
 [4. 4. 3. 2.]] 

Levenshtein Distance = 2.0
